apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mongo
  name: host-pvc
spec:
  selector:
    matchLabels:
      type: local
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-manual