apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mongo
  name: host-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-manual
  hostPath:
    path: "/volume/mongodb"
