apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 10
  selector:
    matchLabels:
      app: application
      env: prd
  template:
    metadata:
      labels:
        app: application
        env: prd
    spec:
      containers:
      - name: application
        image: lfernando88/kubernetes:pythonv1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 90
